version: '3.3'

services:
  server:
    image: ethereum
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: eth
      DB_USER: user
      DB_PASS: password
      BLOCKS_COUNT: 100 #count of checking blocks
      API_KEY:  #add your etherscan.io api key here
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql
    build:
      context: build/mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password